#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantenimientoCrud.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_9E3FAF_CIFASA")]
	public partial class DB_AR_AccountDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertAR_Account(AR_Account instance);
    partial void UpdateAR_Account(AR_Account instance);
    partial void DeleteAR_Account(AR_Account instance);
    #endregion
		
		public DB_AR_AccountDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_AR_AccountDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_AR_AccountDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_AR_AccountDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AR_Account> AR_Account
		{
			get
			{
				return this.GetTable<AR_Account>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ActualizarCuenta")]
		public int sp_ActualizarCuenta([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Company", DbType="NVarChar(50)")] string company, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="City", DbType="NVarChar(50)")] string city, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Country", DbType="NVarChar(30)")] string country, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PhoneNumber", DbType="NVarChar(30)")] string phoneNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(255)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClosingDate", DbType="DateTime")] System.Nullable<System.DateTime> closingDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Notes", DbType="NVarChar(MAX)")] string notes)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, name, company, city, country, phoneNumber, email, closingDate, notes);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_EliminarCuenta")]
		public int sp_EliminarCuenta([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertarCuenta")]
		public int sp_InsertarCuenta(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Number", DbType="NVarChar(20)")] string number, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(50)")] string name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExtCode", DbType="NVarChar(20)")] string extCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Title", DbType="NVarChar(20)")] string title, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstName", DbType="NVarChar(30)")] string firstName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MiddleName", DbType="NVarChar(30)")] string middleName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastName", DbType="NVarChar(50)")] string lastName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Suffix", DbType="NVarChar(20)")] string suffix, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Company", DbType="NVarChar(50)")] string company, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="JobTitle", DbType="NVarChar(50)")] string jobTitle, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address1", DbType="NVarChar(50)")] string address1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address2", DbType="NVarChar(50)")] string address2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="City", DbType="NVarChar(50)")] string city, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="State", DbType="NVarChar(20)")] string state, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Zip", DbType="NVarChar(20)")] string zip, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Country", DbType="NVarChar(30)")] string country, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PhoneNumber", DbType="NVarChar(30)")] string phoneNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MobileNumber", DbType="NVarChar(30)")] string mobileNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FaxNumber", DbType="NVarChar(30)")] string faxNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EMail", DbType="NVarChar(255)")] string eMail, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="HomePage", DbType="NVarChar(255)")] string homePage, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IMAddress", DbType="NVarChar(50)")] string iMAddress, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StatementAddress", DbType="NVarChar(255)")] string statementAddress)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), number, name, extCode, title, firstName, middleName, lastName, suffix, company, jobTitle, address1, address2, city, state, zip, country, phoneNumber, mobileNumber, faxNumber, eMail, homePage, iMAddress, statementAddress);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ObtenerCuenta")]
		public ISingleResult<sp_ObtenerCuentaResult> sp_ObtenerCuenta()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_ObtenerCuentaResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AR_Account")]
	public partial class AR_Account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.DateTime _LastUpdated;
		
		private string _Number;
		
		private string _Name;
		
		private string _ExtCode;
		
		private string _Title;
		
		private string _FirstName;
		
		private string _MiddleName;
		
		private string _LastName;
		
		private string _Suffix;
		
		private string _Company;
		
		private string _JobTitle;
		
		private byte _Type;
		
		private byte _Status;
		
		private int _BillingAccount;
		
		private int _GroupID;
		
		private int _PayTermsID;
		
		private int _FinChargeID;
		
		private int _CurrencyID;
		
		private int _ManagerID;
		
		private int _CountryID;
		
		private int _RegionID;
		
		private int _LocationID;
		
		private string _Address1;
		
		private string _Address2;
		
		private string _City;
		
		private string _State;
		
		private string _Zip;
		
		private string _Country;
		
		private string _PhoneNumber;
		
		private string _MobileNumber;
		
		private string _FaxNumber;
		
		private string _EMail;
		
		private string _HomePage;
		
		private string _IMAddress;
		
		private decimal _CreditLimit;
		
		private byte _CreditLimitCheck;
		
		private int _StatementType;
		
		private byte _StatementDelivery;
		
		private string _StatementAddress;
		
		private byte _ApplicationMethod;
		
		private System.Nullable<System.DateTime> _ClosingDate;
		
		private decimal _ClosingBalance;
		
		private int _LastStatement;
		
		private int _CustomCode1;
		
		private int _CustomCode2;
		
		private int _CustomCode3;
		
		private int _CustomCode4;
		
		private int _CustomCode5;
		
		private string _CustomText1;
		
		private string _CustomText2;
		
		private string _CustomText3;
		
		private string _CustomText4;
		
		private string _CustomText5;
		
		private double _CustomNumber1;
		
		private double _CustomNumber2;
		
		private double _CustomNumber3;
		
		private double _CustomNumber4;
		
		private double _CustomNumber5;
		
		private System.Nullable<System.DateTime> _CustomDate1;
		
		private System.Nullable<System.DateTime> _CustomDate2;
		
		private System.Nullable<System.DateTime> _CustomDate3;
		
		private System.Nullable<System.DateTime> _CustomDate4;
		
		private System.Nullable<System.DateTime> _CustomDate5;
		
		private System.Data.Linq.Binary _Picture;
		
		private string _Notes;
		
		private string _ExtData;
		
		private System.DateTime _DateOpened;
		
		private System.Nullable<System.DateTime> _LastActivity;
		
		private int _ROLE;
		
		private int _StoreID;
		
		private System.Guid _SyncGuid;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnLastUpdatedChanging(System.DateTime value);
    partial void OnLastUpdatedChanged();
    partial void OnNumberChanging(string value);
    partial void OnNumberChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnExtCodeChanging(string value);
    partial void OnExtCodeChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnMiddleNameChanging(string value);
    partial void OnMiddleNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnSuffixChanging(string value);
    partial void OnSuffixChanged();
    partial void OnCompanyChanging(string value);
    partial void OnCompanyChanged();
    partial void OnJobTitleChanging(string value);
    partial void OnJobTitleChanged();
    partial void OnTypeChanging(byte value);
    partial void OnTypeChanged();
    partial void OnStatusChanging(byte value);
    partial void OnStatusChanged();
    partial void OnBillingAccountChanging(int value);
    partial void OnBillingAccountChanged();
    partial void OnGroupIDChanging(int value);
    partial void OnGroupIDChanged();
    partial void OnPayTermsIDChanging(int value);
    partial void OnPayTermsIDChanged();
    partial void OnFinChargeIDChanging(int value);
    partial void OnFinChargeIDChanged();
    partial void OnCurrencyIDChanging(int value);
    partial void OnCurrencyIDChanged();
    partial void OnManagerIDChanging(int value);
    partial void OnManagerIDChanged();
    partial void OnCountryIDChanging(int value);
    partial void OnCountryIDChanged();
    partial void OnRegionIDChanging(int value);
    partial void OnRegionIDChanged();
    partial void OnLocationIDChanging(int value);
    partial void OnLocationIDChanged();
    partial void OnAddress1Changing(string value);
    partial void OnAddress1Changed();
    partial void OnAddress2Changing(string value);
    partial void OnAddress2Changed();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnZipChanging(string value);
    partial void OnZipChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    partial void OnMobileNumberChanging(string value);
    partial void OnMobileNumberChanged();
    partial void OnFaxNumberChanging(string value);
    partial void OnFaxNumberChanged();
    partial void OnEMailChanging(string value);
    partial void OnEMailChanged();
    partial void OnHomePageChanging(string value);
    partial void OnHomePageChanged();
    partial void OnIMAddressChanging(string value);
    partial void OnIMAddressChanged();
    partial void OnCreditLimitChanging(decimal value);
    partial void OnCreditLimitChanged();
    partial void OnCreditLimitCheckChanging(byte value);
    partial void OnCreditLimitCheckChanged();
    partial void OnStatementTypeChanging(int value);
    partial void OnStatementTypeChanged();
    partial void OnStatementDeliveryChanging(byte value);
    partial void OnStatementDeliveryChanged();
    partial void OnStatementAddressChanging(string value);
    partial void OnStatementAddressChanged();
    partial void OnApplicationMethodChanging(byte value);
    partial void OnApplicationMethodChanged();
    partial void OnClosingDateChanging(System.Nullable<System.DateTime> value);
    partial void OnClosingDateChanged();
    partial void OnClosingBalanceChanging(decimal value);
    partial void OnClosingBalanceChanged();
    partial void OnLastStatementChanging(int value);
    partial void OnLastStatementChanged();
    partial void OnCustomCode1Changing(int value);
    partial void OnCustomCode1Changed();
    partial void OnCustomCode2Changing(int value);
    partial void OnCustomCode2Changed();
    partial void OnCustomCode3Changing(int value);
    partial void OnCustomCode3Changed();
    partial void OnCustomCode4Changing(int value);
    partial void OnCustomCode4Changed();
    partial void OnCustomCode5Changing(int value);
    partial void OnCustomCode5Changed();
    partial void OnCustomText1Changing(string value);
    partial void OnCustomText1Changed();
    partial void OnCustomText2Changing(string value);
    partial void OnCustomText2Changed();
    partial void OnCustomText3Changing(string value);
    partial void OnCustomText3Changed();
    partial void OnCustomText4Changing(string value);
    partial void OnCustomText4Changed();
    partial void OnCustomText5Changing(string value);
    partial void OnCustomText5Changed();
    partial void OnCustomNumber1Changing(double value);
    partial void OnCustomNumber1Changed();
    partial void OnCustomNumber2Changing(double value);
    partial void OnCustomNumber2Changed();
    partial void OnCustomNumber3Changing(double value);
    partial void OnCustomNumber3Changed();
    partial void OnCustomNumber4Changing(double value);
    partial void OnCustomNumber4Changed();
    partial void OnCustomNumber5Changing(double value);
    partial void OnCustomNumber5Changed();
    partial void OnCustomDate1Changing(System.Nullable<System.DateTime> value);
    partial void OnCustomDate1Changed();
    partial void OnCustomDate2Changing(System.Nullable<System.DateTime> value);
    partial void OnCustomDate2Changed();
    partial void OnCustomDate3Changing(System.Nullable<System.DateTime> value);
    partial void OnCustomDate3Changed();
    partial void OnCustomDate4Changing(System.Nullable<System.DateTime> value);
    partial void OnCustomDate4Changed();
    partial void OnCustomDate5Changing(System.Nullable<System.DateTime> value);
    partial void OnCustomDate5Changed();
    partial void OnPictureChanging(System.Data.Linq.Binary value);
    partial void OnPictureChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    partial void OnExtDataChanging(string value);
    partial void OnExtDataChanged();
    partial void OnDateOpenedChanging(System.DateTime value);
    partial void OnDateOpenedChanged();
    partial void OnLastActivityChanging(System.Nullable<System.DateTime> value);
    partial void OnLastActivityChanged();
    partial void OnROLEChanging(int value);
    partial void OnROLEChanged();
    partial void OnStoreIDChanging(int value);
    partial void OnStoreIDChanged();
    partial void OnSyncGuidChanging(System.Guid value);
    partial void OnSyncGuidChanged();
    #endregion
		
		public AR_Account()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdated", DbType="DateTime NOT NULL")]
		public System.DateTime LastUpdated
		{
			get
			{
				return this._LastUpdated;
			}
			set
			{
				if ((this._LastUpdated != value))
				{
					this.OnLastUpdatedChanging(value);
					this.SendPropertyChanging();
					this._LastUpdated = value;
					this.SendPropertyChanged("LastUpdated");
					this.OnLastUpdatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this.OnNumberChanging(value);
					this.SendPropertyChanging();
					this._Number = value;
					this.SendPropertyChanged("Number");
					this.OnNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtCode", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ExtCode
		{
			get
			{
				return this._ExtCode;
			}
			set
			{
				if ((this._ExtCode != value))
				{
					this.OnExtCodeChanging(value);
					this.SendPropertyChanging();
					this._ExtCode = value;
					this.SendPropertyChanged("ExtCode");
					this.OnExtCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string MiddleName
		{
			get
			{
				return this._MiddleName;
			}
			set
			{
				if ((this._MiddleName != value))
				{
					this.OnMiddleNameChanging(value);
					this.SendPropertyChanging();
					this._MiddleName = value;
					this.SendPropertyChanged("MiddleName");
					this.OnMiddleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Suffix", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Suffix
		{
			get
			{
				return this._Suffix;
			}
			set
			{
				if ((this._Suffix != value))
				{
					this.OnSuffixChanging(value);
					this.SendPropertyChanging();
					this._Suffix = value;
					this.SendPropertyChanged("Suffix");
					this.OnSuffixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this.OnCompanyChanging(value);
					this.SendPropertyChanging();
					this._Company = value;
					this.SendPropertyChanged("Company");
					this.OnCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobTitle", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string JobTitle
		{
			get
			{
				return this._JobTitle;
			}
			set
			{
				if ((this._JobTitle != value))
				{
					this.OnJobTitleChanging(value);
					this.SendPropertyChanging();
					this._JobTitle = value;
					this.SendPropertyChanged("JobTitle");
					this.OnJobTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="TinyInt NOT NULL")]
		public byte Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="TinyInt NOT NULL")]
		public byte Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingAccount", DbType="Int NOT NULL")]
		public int BillingAccount
		{
			get
			{
				return this._BillingAccount;
			}
			set
			{
				if ((this._BillingAccount != value))
				{
					this.OnBillingAccountChanging(value);
					this.SendPropertyChanging();
					this._BillingAccount = value;
					this.SendPropertyChanged("BillingAccount");
					this.OnBillingAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupID", DbType="Int NOT NULL")]
		public int GroupID
		{
			get
			{
				return this._GroupID;
			}
			set
			{
				if ((this._GroupID != value))
				{
					this.OnGroupIDChanging(value);
					this.SendPropertyChanging();
					this._GroupID = value;
					this.SendPropertyChanged("GroupID");
					this.OnGroupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayTermsID", DbType="Int NOT NULL")]
		public int PayTermsID
		{
			get
			{
				return this._PayTermsID;
			}
			set
			{
				if ((this._PayTermsID != value))
				{
					this.OnPayTermsIDChanging(value);
					this.SendPropertyChanging();
					this._PayTermsID = value;
					this.SendPropertyChanged("PayTermsID");
					this.OnPayTermsIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinChargeID", DbType="Int NOT NULL")]
		public int FinChargeID
		{
			get
			{
				return this._FinChargeID;
			}
			set
			{
				if ((this._FinChargeID != value))
				{
					this.OnFinChargeIDChanging(value);
					this.SendPropertyChanging();
					this._FinChargeID = value;
					this.SendPropertyChanged("FinChargeID");
					this.OnFinChargeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrencyID", DbType="Int NOT NULL")]
		public int CurrencyID
		{
			get
			{
				return this._CurrencyID;
			}
			set
			{
				if ((this._CurrencyID != value))
				{
					this.OnCurrencyIDChanging(value);
					this.SendPropertyChanging();
					this._CurrencyID = value;
					this.SendPropertyChanged("CurrencyID");
					this.OnCurrencyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManagerID", DbType="Int NOT NULL")]
		public int ManagerID
		{
			get
			{
				return this._ManagerID;
			}
			set
			{
				if ((this._ManagerID != value))
				{
					this.OnManagerIDChanging(value);
					this.SendPropertyChanging();
					this._ManagerID = value;
					this.SendPropertyChanged("ManagerID");
					this.OnManagerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryID", DbType="Int NOT NULL")]
		public int CountryID
		{
			get
			{
				return this._CountryID;
			}
			set
			{
				if ((this._CountryID != value))
				{
					this.OnCountryIDChanging(value);
					this.SendPropertyChanging();
					this._CountryID = value;
					this.SendPropertyChanged("CountryID");
					this.OnCountryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegionID", DbType="Int NOT NULL")]
		public int RegionID
		{
			get
			{
				return this._RegionID;
			}
			set
			{
				if ((this._RegionID != value))
				{
					this.OnRegionIDChanging(value);
					this.SendPropertyChanging();
					this._RegionID = value;
					this.SendPropertyChanged("RegionID");
					this.OnRegionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationID", DbType="Int NOT NULL")]
		public int LocationID
		{
			get
			{
				return this._LocationID;
			}
			set
			{
				if ((this._LocationID != value))
				{
					this.OnLocationIDChanging(value);
					this.SendPropertyChanging();
					this._LocationID = value;
					this.SendPropertyChanged("LocationID");
					this.OnLocationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this.OnAddress1Changing(value);
					this.SendPropertyChanging();
					this._Address1 = value;
					this.SendPropertyChanged("Address1");
					this.OnAddress1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this.OnAddress2Changing(value);
					this.SendPropertyChanging();
					this._Address2 = value;
					this.SendPropertyChanged("Address2");
					this.OnAddress2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Zip
		{
			get
			{
				return this._Zip;
			}
			set
			{
				if ((this._Zip != value))
				{
					this.OnZipChanging(value);
					this.SendPropertyChanging();
					this._Zip = value;
					this.SendPropertyChanged("Zip");
					this.OnZipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNumber", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string MobileNumber
		{
			get
			{
				return this._MobileNumber;
			}
			set
			{
				if ((this._MobileNumber != value))
				{
					this.OnMobileNumberChanging(value);
					this.SendPropertyChanging();
					this._MobileNumber = value;
					this.SendPropertyChanged("MobileNumber");
					this.OnMobileNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaxNumber", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string FaxNumber
		{
			get
			{
				return this._FaxNumber;
			}
			set
			{
				if ((this._FaxNumber != value))
				{
					this.OnFaxNumberChanging(value);
					this.SendPropertyChanging();
					this._FaxNumber = value;
					this.SendPropertyChanged("FaxNumber");
					this.OnFaxNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMail", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string EMail
		{
			get
			{
				return this._EMail;
			}
			set
			{
				if ((this._EMail != value))
				{
					this.OnEMailChanging(value);
					this.SendPropertyChanging();
					this._EMail = value;
					this.SendPropertyChanged("EMail");
					this.OnEMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomePage", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string HomePage
		{
			get
			{
				return this._HomePage;
			}
			set
			{
				if ((this._HomePage != value))
				{
					this.OnHomePageChanging(value);
					this.SendPropertyChanging();
					this._HomePage = value;
					this.SendPropertyChanged("HomePage");
					this.OnHomePageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMAddress", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string IMAddress
		{
			get
			{
				return this._IMAddress;
			}
			set
			{
				if ((this._IMAddress != value))
				{
					this.OnIMAddressChanging(value);
					this.SendPropertyChanging();
					this._IMAddress = value;
					this.SendPropertyChanged("IMAddress");
					this.OnIMAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditLimit", DbType="Money NOT NULL")]
		public decimal CreditLimit
		{
			get
			{
				return this._CreditLimit;
			}
			set
			{
				if ((this._CreditLimit != value))
				{
					this.OnCreditLimitChanging(value);
					this.SendPropertyChanging();
					this._CreditLimit = value;
					this.SendPropertyChanged("CreditLimit");
					this.OnCreditLimitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditLimitCheck", DbType="TinyInt NOT NULL")]
		public byte CreditLimitCheck
		{
			get
			{
				return this._CreditLimitCheck;
			}
			set
			{
				if ((this._CreditLimitCheck != value))
				{
					this.OnCreditLimitCheckChanging(value);
					this.SendPropertyChanging();
					this._CreditLimitCheck = value;
					this.SendPropertyChanged("CreditLimitCheck");
					this.OnCreditLimitCheckChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatementType", DbType="Int NOT NULL")]
		public int StatementType
		{
			get
			{
				return this._StatementType;
			}
			set
			{
				if ((this._StatementType != value))
				{
					this.OnStatementTypeChanging(value);
					this.SendPropertyChanging();
					this._StatementType = value;
					this.SendPropertyChanged("StatementType");
					this.OnStatementTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatementDelivery", DbType="TinyInt NOT NULL")]
		public byte StatementDelivery
		{
			get
			{
				return this._StatementDelivery;
			}
			set
			{
				if ((this._StatementDelivery != value))
				{
					this.OnStatementDeliveryChanging(value);
					this.SendPropertyChanging();
					this._StatementDelivery = value;
					this.SendPropertyChanged("StatementDelivery");
					this.OnStatementDeliveryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatementAddress", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string StatementAddress
		{
			get
			{
				return this._StatementAddress;
			}
			set
			{
				if ((this._StatementAddress != value))
				{
					this.OnStatementAddressChanging(value);
					this.SendPropertyChanging();
					this._StatementAddress = value;
					this.SendPropertyChanged("StatementAddress");
					this.OnStatementAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationMethod", DbType="TinyInt NOT NULL")]
		public byte ApplicationMethod
		{
			get
			{
				return this._ApplicationMethod;
			}
			set
			{
				if ((this._ApplicationMethod != value))
				{
					this.OnApplicationMethodChanging(value);
					this.SendPropertyChanging();
					this._ApplicationMethod = value;
					this.SendPropertyChanged("ApplicationMethod");
					this.OnApplicationMethodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClosingDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ClosingDate
		{
			get
			{
				return this._ClosingDate;
			}
			set
			{
				if ((this._ClosingDate != value))
				{
					this.OnClosingDateChanging(value);
					this.SendPropertyChanging();
					this._ClosingDate = value;
					this.SendPropertyChanged("ClosingDate");
					this.OnClosingDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClosingBalance", DbType="Money NOT NULL")]
		public decimal ClosingBalance
		{
			get
			{
				return this._ClosingBalance;
			}
			set
			{
				if ((this._ClosingBalance != value))
				{
					this.OnClosingBalanceChanging(value);
					this.SendPropertyChanging();
					this._ClosingBalance = value;
					this.SendPropertyChanged("ClosingBalance");
					this.OnClosingBalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastStatement", DbType="Int NOT NULL")]
		public int LastStatement
		{
			get
			{
				return this._LastStatement;
			}
			set
			{
				if ((this._LastStatement != value))
				{
					this.OnLastStatementChanging(value);
					this.SendPropertyChanging();
					this._LastStatement = value;
					this.SendPropertyChanged("LastStatement");
					this.OnLastStatementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomCode1", DbType="Int NOT NULL")]
		public int CustomCode1
		{
			get
			{
				return this._CustomCode1;
			}
			set
			{
				if ((this._CustomCode1 != value))
				{
					this.OnCustomCode1Changing(value);
					this.SendPropertyChanging();
					this._CustomCode1 = value;
					this.SendPropertyChanged("CustomCode1");
					this.OnCustomCode1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomCode2", DbType="Int NOT NULL")]
		public int CustomCode2
		{
			get
			{
				return this._CustomCode2;
			}
			set
			{
				if ((this._CustomCode2 != value))
				{
					this.OnCustomCode2Changing(value);
					this.SendPropertyChanging();
					this._CustomCode2 = value;
					this.SendPropertyChanged("CustomCode2");
					this.OnCustomCode2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomCode3", DbType="Int NOT NULL")]
		public int CustomCode3
		{
			get
			{
				return this._CustomCode3;
			}
			set
			{
				if ((this._CustomCode3 != value))
				{
					this.OnCustomCode3Changing(value);
					this.SendPropertyChanging();
					this._CustomCode3 = value;
					this.SendPropertyChanged("CustomCode3");
					this.OnCustomCode3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomCode4", DbType="Int NOT NULL")]
		public int CustomCode4
		{
			get
			{
				return this._CustomCode4;
			}
			set
			{
				if ((this._CustomCode4 != value))
				{
					this.OnCustomCode4Changing(value);
					this.SendPropertyChanging();
					this._CustomCode4 = value;
					this.SendPropertyChanged("CustomCode4");
					this.OnCustomCode4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomCode5", DbType="Int NOT NULL")]
		public int CustomCode5
		{
			get
			{
				return this._CustomCode5;
			}
			set
			{
				if ((this._CustomCode5 != value))
				{
					this.OnCustomCode5Changing(value);
					this.SendPropertyChanging();
					this._CustomCode5 = value;
					this.SendPropertyChanged("CustomCode5");
					this.OnCustomCode5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomText1", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string CustomText1
		{
			get
			{
				return this._CustomText1;
			}
			set
			{
				if ((this._CustomText1 != value))
				{
					this.OnCustomText1Changing(value);
					this.SendPropertyChanging();
					this._CustomText1 = value;
					this.SendPropertyChanged("CustomText1");
					this.OnCustomText1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomText2", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string CustomText2
		{
			get
			{
				return this._CustomText2;
			}
			set
			{
				if ((this._CustomText2 != value))
				{
					this.OnCustomText2Changing(value);
					this.SendPropertyChanging();
					this._CustomText2 = value;
					this.SendPropertyChanged("CustomText2");
					this.OnCustomText2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomText3", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string CustomText3
		{
			get
			{
				return this._CustomText3;
			}
			set
			{
				if ((this._CustomText3 != value))
				{
					this.OnCustomText3Changing(value);
					this.SendPropertyChanging();
					this._CustomText3 = value;
					this.SendPropertyChanged("CustomText3");
					this.OnCustomText3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomText4", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string CustomText4
		{
			get
			{
				return this._CustomText4;
			}
			set
			{
				if ((this._CustomText4 != value))
				{
					this.OnCustomText4Changing(value);
					this.SendPropertyChanging();
					this._CustomText4 = value;
					this.SendPropertyChanged("CustomText4");
					this.OnCustomText4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomText5", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string CustomText5
		{
			get
			{
				return this._CustomText5;
			}
			set
			{
				if ((this._CustomText5 != value))
				{
					this.OnCustomText5Changing(value);
					this.SendPropertyChanging();
					this._CustomText5 = value;
					this.SendPropertyChanged("CustomText5");
					this.OnCustomText5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomNumber1", DbType="Float NOT NULL")]
		public double CustomNumber1
		{
			get
			{
				return this._CustomNumber1;
			}
			set
			{
				if ((this._CustomNumber1 != value))
				{
					this.OnCustomNumber1Changing(value);
					this.SendPropertyChanging();
					this._CustomNumber1 = value;
					this.SendPropertyChanged("CustomNumber1");
					this.OnCustomNumber1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomNumber2", DbType="Float NOT NULL")]
		public double CustomNumber2
		{
			get
			{
				return this._CustomNumber2;
			}
			set
			{
				if ((this._CustomNumber2 != value))
				{
					this.OnCustomNumber2Changing(value);
					this.SendPropertyChanging();
					this._CustomNumber2 = value;
					this.SendPropertyChanged("CustomNumber2");
					this.OnCustomNumber2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomNumber3", DbType="Float NOT NULL")]
		public double CustomNumber3
		{
			get
			{
				return this._CustomNumber3;
			}
			set
			{
				if ((this._CustomNumber3 != value))
				{
					this.OnCustomNumber3Changing(value);
					this.SendPropertyChanging();
					this._CustomNumber3 = value;
					this.SendPropertyChanged("CustomNumber3");
					this.OnCustomNumber3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomNumber4", DbType="Float NOT NULL")]
		public double CustomNumber4
		{
			get
			{
				return this._CustomNumber4;
			}
			set
			{
				if ((this._CustomNumber4 != value))
				{
					this.OnCustomNumber4Changing(value);
					this.SendPropertyChanging();
					this._CustomNumber4 = value;
					this.SendPropertyChanged("CustomNumber4");
					this.OnCustomNumber4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomNumber5", DbType="Float NOT NULL")]
		public double CustomNumber5
		{
			get
			{
				return this._CustomNumber5;
			}
			set
			{
				if ((this._CustomNumber5 != value))
				{
					this.OnCustomNumber5Changing(value);
					this.SendPropertyChanging();
					this._CustomNumber5 = value;
					this.SendPropertyChanged("CustomNumber5");
					this.OnCustomNumber5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomDate1", DbType="DateTime")]
		public System.Nullable<System.DateTime> CustomDate1
		{
			get
			{
				return this._CustomDate1;
			}
			set
			{
				if ((this._CustomDate1 != value))
				{
					this.OnCustomDate1Changing(value);
					this.SendPropertyChanging();
					this._CustomDate1 = value;
					this.SendPropertyChanged("CustomDate1");
					this.OnCustomDate1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomDate2", DbType="DateTime")]
		public System.Nullable<System.DateTime> CustomDate2
		{
			get
			{
				return this._CustomDate2;
			}
			set
			{
				if ((this._CustomDate2 != value))
				{
					this.OnCustomDate2Changing(value);
					this.SendPropertyChanging();
					this._CustomDate2 = value;
					this.SendPropertyChanged("CustomDate2");
					this.OnCustomDate2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomDate3", DbType="DateTime")]
		public System.Nullable<System.DateTime> CustomDate3
		{
			get
			{
				return this._CustomDate3;
			}
			set
			{
				if ((this._CustomDate3 != value))
				{
					this.OnCustomDate3Changing(value);
					this.SendPropertyChanging();
					this._CustomDate3 = value;
					this.SendPropertyChanged("CustomDate3");
					this.OnCustomDate3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomDate4", DbType="DateTime")]
		public System.Nullable<System.DateTime> CustomDate4
		{
			get
			{
				return this._CustomDate4;
			}
			set
			{
				if ((this._CustomDate4 != value))
				{
					this.OnCustomDate4Changing(value);
					this.SendPropertyChanging();
					this._CustomDate4 = value;
					this.SendPropertyChanged("CustomDate4");
					this.OnCustomDate4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomDate5", DbType="DateTime")]
		public System.Nullable<System.DateTime> CustomDate5
		{
			get
			{
				return this._CustomDate5;
			}
			set
			{
				if ((this._CustomDate5 != value))
				{
					this.OnCustomDate5Changing(value);
					this.SendPropertyChanging();
					this._CustomDate5 = value;
					this.SendPropertyChanged("CustomDate5");
					this.OnCustomDate5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Picture
		{
			get
			{
				return this._Picture;
			}
			set
			{
				if ((this._Picture != value))
				{
					this.OnPictureChanging(value);
					this.SendPropertyChanging();
					this._Picture = value;
					this.SendPropertyChanged("Picture");
					this.OnPictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NVarChar(MAX)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtData", DbType="NVarChar(MAX)")]
		public string ExtData
		{
			get
			{
				return this._ExtData;
			}
			set
			{
				if ((this._ExtData != value))
				{
					this.OnExtDataChanging(value);
					this.SendPropertyChanging();
					this._ExtData = value;
					this.SendPropertyChanged("ExtData");
					this.OnExtDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOpened", DbType="DateTime NOT NULL")]
		public System.DateTime DateOpened
		{
			get
			{
				return this._DateOpened;
			}
			set
			{
				if ((this._DateOpened != value))
				{
					this.OnDateOpenedChanging(value);
					this.SendPropertyChanging();
					this._DateOpened = value;
					this.SendPropertyChanged("DateOpened");
					this.OnDateOpenedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastActivity", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastActivity
		{
			get
			{
				return this._LastActivity;
			}
			set
			{
				if ((this._LastActivity != value))
				{
					this.OnLastActivityChanging(value);
					this.SendPropertyChanging();
					this._LastActivity = value;
					this.SendPropertyChanged("LastActivity");
					this.OnLastActivityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROLE", AutoSync=AutoSync.Always, DbType="Int NOT NULL", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int ROLE
		{
			get
			{
				return this._ROLE;
			}
			set
			{
				if ((this._ROLE != value))
				{
					this.OnROLEChanging(value);
					this.SendPropertyChanging();
					this._ROLE = value;
					this.SendPropertyChanged("ROLE");
					this.OnROLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreID", DbType="Int NOT NULL")]
		public int StoreID
		{
			get
			{
				return this._StoreID;
			}
			set
			{
				if ((this._StoreID != value))
				{
					this.OnStoreIDChanging(value);
					this.SendPropertyChanging();
					this._StoreID = value;
					this.SendPropertyChanged("StoreID");
					this.OnStoreIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SyncGuid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid SyncGuid
		{
			get
			{
				return this._SyncGuid;
			}
			set
			{
				if ((this._SyncGuid != value))
				{
					this.OnSyncGuidChanging(value);
					this.SendPropertyChanging();
					this._SyncGuid = value;
					this.SendPropertyChanged("SyncGuid");
					this.OnSyncGuidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sp_ObtenerCuentaResult
	{
		
		private int _ID;
		
		private System.DateTime _LastUpdated;
		
		private string _Number;
		
		private string _Name;
		
		private string _ExtCode;
		
		private string _Title;
		
		private string _FirstName;
		
		private string _MiddleName;
		
		private string _LastName;
		
		private string _Suffix;
		
		private string _Company;
		
		private string _JobTitle;
		
		private byte _Type;
		
		private byte _Status;
		
		private int _BillingAccount;
		
		private int _GroupID;
		
		private int _PayTermsID;
		
		private int _FinChargeID;
		
		private int _CurrencyID;
		
		private int _ManagerID;
		
		private int _CountryID;
		
		private int _RegionID;
		
		private int _LocationID;
		
		private string _Address1;
		
		private string _Address2;
		
		private string _City;
		
		private string _State;
		
		private string _Zip;
		
		private string _Country;
		
		private string _PhoneNumber;
		
		private string _MobileNumber;
		
		private string _FaxNumber;
		
		private string _EMail;
		
		private string _HomePage;
		
		private string _IMAddress;
		
		private decimal _CreditLimit;
		
		private byte _CreditLimitCheck;
		
		private int _StatementType;
		
		private byte _StatementDelivery;
		
		private string _StatementAddress;
		
		private byte _ApplicationMethod;
		
		private System.Nullable<System.DateTime> _ClosingDate;
		
		private decimal _ClosingBalance;
		
		private int _LastStatement;
		
		private int _CustomCode1;
		
		private int _CustomCode2;
		
		private int _CustomCode3;
		
		private int _CustomCode4;
		
		private int _CustomCode5;
		
		private string _CustomText1;
		
		private string _CustomText2;
		
		private string _CustomText3;
		
		private string _CustomText4;
		
		private string _CustomText5;
		
		private double _CustomNumber1;
		
		private double _CustomNumber2;
		
		private double _CustomNumber3;
		
		private double _CustomNumber4;
		
		private double _CustomNumber5;
		
		private System.Nullable<System.DateTime> _CustomDate1;
		
		private System.Nullable<System.DateTime> _CustomDate2;
		
		private System.Nullable<System.DateTime> _CustomDate3;
		
		private System.Nullable<System.DateTime> _CustomDate4;
		
		private System.Nullable<System.DateTime> _CustomDate5;
		
		private System.Data.Linq.Binary _Picture;
		
		private string _Notes;
		
		private string _ExtData;
		
		private System.DateTime _DateOpened;
		
		private System.Nullable<System.DateTime> _LastActivity;
		
		private int _ROLE;
		
		private int _StoreID;
		
		private System.Guid _SyncGuid;
		
		public sp_ObtenerCuentaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdated", DbType="DateTime NOT NULL")]
		public System.DateTime LastUpdated
		{
			get
			{
				return this._LastUpdated;
			}
			set
			{
				if ((this._LastUpdated != value))
				{
					this._LastUpdated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this._Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtCode", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ExtCode
		{
			get
			{
				return this._ExtCode;
			}
			set
			{
				if ((this._ExtCode != value))
				{
					this._ExtCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string MiddleName
		{
			get
			{
				return this._MiddleName;
			}
			set
			{
				if ((this._MiddleName != value))
				{
					this._MiddleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Suffix", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Suffix
		{
			get
			{
				return this._Suffix;
			}
			set
			{
				if ((this._Suffix != value))
				{
					this._Suffix = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this._Company = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobTitle", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string JobTitle
		{
			get
			{
				return this._JobTitle;
			}
			set
			{
				if ((this._JobTitle != value))
				{
					this._JobTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="TinyInt NOT NULL")]
		public byte Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="TinyInt NOT NULL")]
		public byte Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingAccount", DbType="Int NOT NULL")]
		public int BillingAccount
		{
			get
			{
				return this._BillingAccount;
			}
			set
			{
				if ((this._BillingAccount != value))
				{
					this._BillingAccount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupID", DbType="Int NOT NULL")]
		public int GroupID
		{
			get
			{
				return this._GroupID;
			}
			set
			{
				if ((this._GroupID != value))
				{
					this._GroupID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayTermsID", DbType="Int NOT NULL")]
		public int PayTermsID
		{
			get
			{
				return this._PayTermsID;
			}
			set
			{
				if ((this._PayTermsID != value))
				{
					this._PayTermsID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinChargeID", DbType="Int NOT NULL")]
		public int FinChargeID
		{
			get
			{
				return this._FinChargeID;
			}
			set
			{
				if ((this._FinChargeID != value))
				{
					this._FinChargeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrencyID", DbType="Int NOT NULL")]
		public int CurrencyID
		{
			get
			{
				return this._CurrencyID;
			}
			set
			{
				if ((this._CurrencyID != value))
				{
					this._CurrencyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManagerID", DbType="Int NOT NULL")]
		public int ManagerID
		{
			get
			{
				return this._ManagerID;
			}
			set
			{
				if ((this._ManagerID != value))
				{
					this._ManagerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryID", DbType="Int NOT NULL")]
		public int CountryID
		{
			get
			{
				return this._CountryID;
			}
			set
			{
				if ((this._CountryID != value))
				{
					this._CountryID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegionID", DbType="Int NOT NULL")]
		public int RegionID
		{
			get
			{
				return this._RegionID;
			}
			set
			{
				if ((this._RegionID != value))
				{
					this._RegionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationID", DbType="Int NOT NULL")]
		public int LocationID
		{
			get
			{
				return this._LocationID;
			}
			set
			{
				if ((this._LocationID != value))
				{
					this._LocationID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this._Address1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this._Address2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Zip
		{
			get
			{
				return this._Zip;
			}
			set
			{
				if ((this._Zip != value))
				{
					this._Zip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this._Country = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this._PhoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNumber", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string MobileNumber
		{
			get
			{
				return this._MobileNumber;
			}
			set
			{
				if ((this._MobileNumber != value))
				{
					this._MobileNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaxNumber", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string FaxNumber
		{
			get
			{
				return this._FaxNumber;
			}
			set
			{
				if ((this._FaxNumber != value))
				{
					this._FaxNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMail", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string EMail
		{
			get
			{
				return this._EMail;
			}
			set
			{
				if ((this._EMail != value))
				{
					this._EMail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomePage", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string HomePage
		{
			get
			{
				return this._HomePage;
			}
			set
			{
				if ((this._HomePage != value))
				{
					this._HomePage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMAddress", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string IMAddress
		{
			get
			{
				return this._IMAddress;
			}
			set
			{
				if ((this._IMAddress != value))
				{
					this._IMAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditLimit", DbType="Money NOT NULL")]
		public decimal CreditLimit
		{
			get
			{
				return this._CreditLimit;
			}
			set
			{
				if ((this._CreditLimit != value))
				{
					this._CreditLimit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditLimitCheck", DbType="TinyInt NOT NULL")]
		public byte CreditLimitCheck
		{
			get
			{
				return this._CreditLimitCheck;
			}
			set
			{
				if ((this._CreditLimitCheck != value))
				{
					this._CreditLimitCheck = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatementType", DbType="Int NOT NULL")]
		public int StatementType
		{
			get
			{
				return this._StatementType;
			}
			set
			{
				if ((this._StatementType != value))
				{
					this._StatementType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatementDelivery", DbType="TinyInt NOT NULL")]
		public byte StatementDelivery
		{
			get
			{
				return this._StatementDelivery;
			}
			set
			{
				if ((this._StatementDelivery != value))
				{
					this._StatementDelivery = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatementAddress", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string StatementAddress
		{
			get
			{
				return this._StatementAddress;
			}
			set
			{
				if ((this._StatementAddress != value))
				{
					this._StatementAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationMethod", DbType="TinyInt NOT NULL")]
		public byte ApplicationMethod
		{
			get
			{
				return this._ApplicationMethod;
			}
			set
			{
				if ((this._ApplicationMethod != value))
				{
					this._ApplicationMethod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClosingDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ClosingDate
		{
			get
			{
				return this._ClosingDate;
			}
			set
			{
				if ((this._ClosingDate != value))
				{
					this._ClosingDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClosingBalance", DbType="Money NOT NULL")]
		public decimal ClosingBalance
		{
			get
			{
				return this._ClosingBalance;
			}
			set
			{
				if ((this._ClosingBalance != value))
				{
					this._ClosingBalance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastStatement", DbType="Int NOT NULL")]
		public int LastStatement
		{
			get
			{
				return this._LastStatement;
			}
			set
			{
				if ((this._LastStatement != value))
				{
					this._LastStatement = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomCode1", DbType="Int NOT NULL")]
		public int CustomCode1
		{
			get
			{
				return this._CustomCode1;
			}
			set
			{
				if ((this._CustomCode1 != value))
				{
					this._CustomCode1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomCode2", DbType="Int NOT NULL")]
		public int CustomCode2
		{
			get
			{
				return this._CustomCode2;
			}
			set
			{
				if ((this._CustomCode2 != value))
				{
					this._CustomCode2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomCode3", DbType="Int NOT NULL")]
		public int CustomCode3
		{
			get
			{
				return this._CustomCode3;
			}
			set
			{
				if ((this._CustomCode3 != value))
				{
					this._CustomCode3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomCode4", DbType="Int NOT NULL")]
		public int CustomCode4
		{
			get
			{
				return this._CustomCode4;
			}
			set
			{
				if ((this._CustomCode4 != value))
				{
					this._CustomCode4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomCode5", DbType="Int NOT NULL")]
		public int CustomCode5
		{
			get
			{
				return this._CustomCode5;
			}
			set
			{
				if ((this._CustomCode5 != value))
				{
					this._CustomCode5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomText1", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string CustomText1
		{
			get
			{
				return this._CustomText1;
			}
			set
			{
				if ((this._CustomText1 != value))
				{
					this._CustomText1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomText2", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string CustomText2
		{
			get
			{
				return this._CustomText2;
			}
			set
			{
				if ((this._CustomText2 != value))
				{
					this._CustomText2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomText3", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string CustomText3
		{
			get
			{
				return this._CustomText3;
			}
			set
			{
				if ((this._CustomText3 != value))
				{
					this._CustomText3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomText4", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string CustomText4
		{
			get
			{
				return this._CustomText4;
			}
			set
			{
				if ((this._CustomText4 != value))
				{
					this._CustomText4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomText5", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string CustomText5
		{
			get
			{
				return this._CustomText5;
			}
			set
			{
				if ((this._CustomText5 != value))
				{
					this._CustomText5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomNumber1", DbType="Float NOT NULL")]
		public double CustomNumber1
		{
			get
			{
				return this._CustomNumber1;
			}
			set
			{
				if ((this._CustomNumber1 != value))
				{
					this._CustomNumber1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomNumber2", DbType="Float NOT NULL")]
		public double CustomNumber2
		{
			get
			{
				return this._CustomNumber2;
			}
			set
			{
				if ((this._CustomNumber2 != value))
				{
					this._CustomNumber2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomNumber3", DbType="Float NOT NULL")]
		public double CustomNumber3
		{
			get
			{
				return this._CustomNumber3;
			}
			set
			{
				if ((this._CustomNumber3 != value))
				{
					this._CustomNumber3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomNumber4", DbType="Float NOT NULL")]
		public double CustomNumber4
		{
			get
			{
				return this._CustomNumber4;
			}
			set
			{
				if ((this._CustomNumber4 != value))
				{
					this._CustomNumber4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomNumber5", DbType="Float NOT NULL")]
		public double CustomNumber5
		{
			get
			{
				return this._CustomNumber5;
			}
			set
			{
				if ((this._CustomNumber5 != value))
				{
					this._CustomNumber5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomDate1", DbType="DateTime")]
		public System.Nullable<System.DateTime> CustomDate1
		{
			get
			{
				return this._CustomDate1;
			}
			set
			{
				if ((this._CustomDate1 != value))
				{
					this._CustomDate1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomDate2", DbType="DateTime")]
		public System.Nullable<System.DateTime> CustomDate2
		{
			get
			{
				return this._CustomDate2;
			}
			set
			{
				if ((this._CustomDate2 != value))
				{
					this._CustomDate2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomDate3", DbType="DateTime")]
		public System.Nullable<System.DateTime> CustomDate3
		{
			get
			{
				return this._CustomDate3;
			}
			set
			{
				if ((this._CustomDate3 != value))
				{
					this._CustomDate3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomDate4", DbType="DateTime")]
		public System.Nullable<System.DateTime> CustomDate4
		{
			get
			{
				return this._CustomDate4;
			}
			set
			{
				if ((this._CustomDate4 != value))
				{
					this._CustomDate4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomDate5", DbType="DateTime")]
		public System.Nullable<System.DateTime> CustomDate5
		{
			get
			{
				return this._CustomDate5;
			}
			set
			{
				if ((this._CustomDate5 != value))
				{
					this._CustomDate5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary Picture
		{
			get
			{
				return this._Picture;
			}
			set
			{
				if ((this._Picture != value))
				{
					this._Picture = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NVarChar(MAX)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this._Notes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtData", DbType="NVarChar(MAX)")]
		public string ExtData
		{
			get
			{
				return this._ExtData;
			}
			set
			{
				if ((this._ExtData != value))
				{
					this._ExtData = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOpened", DbType="DateTime NOT NULL")]
		public System.DateTime DateOpened
		{
			get
			{
				return this._DateOpened;
			}
			set
			{
				if ((this._DateOpened != value))
				{
					this._DateOpened = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastActivity", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastActivity
		{
			get
			{
				return this._LastActivity;
			}
			set
			{
				if ((this._LastActivity != value))
				{
					this._LastActivity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROLE", DbType="Int NOT NULL")]
		public int ROLE
		{
			get
			{
				return this._ROLE;
			}
			set
			{
				if ((this._ROLE != value))
				{
					this._ROLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreID", DbType="Int NOT NULL")]
		public int StoreID
		{
			get
			{
				return this._StoreID;
			}
			set
			{
				if ((this._StoreID != value))
				{
					this._StoreID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SyncGuid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid SyncGuid
		{
			get
			{
				return this._SyncGuid;
			}
			set
			{
				if ((this._SyncGuid != value))
				{
					this._SyncGuid = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
